### ISSUE TITLE
Vulnerable dependency

### ISSUE THREAD

**Issue by artyom** [Doist/eslint-plugin-doist#3]
Github has been reporting dependency vulnerability for more than a month:

<img width="527" alt="Screen Shot 2020-03-03 at 12 06 21" src="https://user-images.githubusercontent.com/68182/75759933-682c0d00-5d47-11ea-9381-bcecb7e92634.png">

**Comment by stkao05** [comment]
Addressed [here](https://github.com/Doist/eslint-plugin-doist/pull/2). Thanks for pining @artyom
